addSbtPlugin("org.scalameta"  % "sbt-scalafmt"  % "2.6.1")
addSbtPlugin("ch.epfl.scala"  % "sbt-scalafix"  % "0.14.5")
addSbtPlugin("com.github.sbt" % "sbt-dynver"    % "5.1.1")
addSbtPlugin("com.github.sbt" % "sbt-pgp"       % "2.3.1")
addSbtPlugin("org.scoverage"  % "sbt-scoverage" % "2.4.4")
